load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_test")

go_binary(
    name = "write-notices",
    srcs = [
        "main.go",
        "notices.go",
    ],
    pure = "on",
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "@platforms//os:macos": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    visibility = ["//:__subpackages__"],
    deps = [
        "//supply_chain/private/tools/internal/cli:lib",
        "//supply_chain/private/tools/internal/jsondata:lib",
        "//supply_chain/private/tools/internal/metadata:lib",
        "//supply_chain/private/tools/internal/policy:lib",
        "//supply_chain/private/tools/internal/purl:lib",
    ],
)

go_test(
    name = "unit_test",
    srcs = [
        "main.go",
        "notices.go",
        "notices_test.go",
    ],
    pure = "on",
    race = "off",
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "@platforms//os:macos": [],
        "@platforms//os:windows": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "//supply_chain/private/tools/internal/cli:lib",
        "//supply_chain/private/tools/internal/jsondata:lib",
        "//supply_chain/private/tools/internal/metadata:lib",
        "//supply_chain/private/tools/internal/policy:lib",
        "//supply_chain/private/tools/internal/purl:lib",
        "//supply_chain/private/tools/internal/testfs:lib",
    ],
)

go_test(
    name = "unit_race_test",
    srcs = [
        "main.go",
        "notices.go",
        "notices_test.go",
    ],
    pure = "off",
    race = "on",
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "@platforms//os:macos": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "//supply_chain/private/tools/internal/cli:lib",
        "//supply_chain/private/tools/internal/jsondata:lib",
        "//supply_chain/private/tools/internal/metadata:lib",
        "//supply_chain/private/tools/internal/policy:lib",
        "//supply_chain/private/tools/internal/purl:lib",
        "//supply_chain/private/tools/internal/testfs:lib",
    ],
)

test_suite(
    name = "runtime_test",
    tests = [
        ":unit_race_test",
        ":unit_test",
    ],
    visibility = ["//supply_chain/private/tools:__pkg__"],
)
