load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")
load("//supply_chain/private:supply_chain_test.bzl", "replay_source")

go_binary(
    name = "replay-verdict",
    srcs = [
        "main.go",
        "replay.go",
    ],
    pure = "on",
    target_compatible_with = [],
    visibility = ["//:__subpackages__"],
    deps = [
        "//supply_chain/private/tools/internal/cli:lib",
    ],
)

go_test(
    name = "unit_test",
    srcs = [
        "main.go",
        "replay.go",
        "replay_test.go",
    ],
    pure = "on",
    race = "off",
    target_compatible_with = [],
    deps = [
        "//supply_chain/private/tools/internal/cli:lib",
        "//supply_chain/private/tools/internal/testfs:lib",
    ],
)

go_test(
    name = "unit_race_test",
    srcs = [
        "main.go",
        "replay.go",
        "replay_test.go",
    ],
    pure = "off",
    race = "on",
    target_compatible_with = select({
        "@platforms//os:windows": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "//supply_chain/private/tools/internal/cli:lib",
        "//supply_chain/private/tools/internal/testfs:lib",
    ],
)

test_suite(
    name = "runtime_test",
    tests = [
        ":unit_race_test",
        ":unit_test",
    ],
    visibility = ["//supply_chain/private/tools:__pkg__"],
)

go_library(
    name = "source",
    srcs = [
        "main.go",
        "replay.go",
    ],
    importpath = "github.com/latticebuild/rules_supply_chain/supply_chain/private/tools/replay-verdict",
    target_compatible_with = [],
    visibility = ["//:__subpackages__"],
    deps = ["//supply_chain/private/tools/internal/cli:lib"],
)

replay_source(
    name = "source_context",
    source = ":source",
    visibility = ["//:__subpackages__"],
)
