load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "lib",
    srcs = [
        "cli.go",
    ],
    importpath = "github.com/latticebuild/rules_supply_chain/supply_chain/private/tools/internal/cli",
    target_compatible_with = [],
    visibility = ["//supply_chain/private/tools:__subpackages__"],
)
