load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "lib",
    srcs = [
        "purl.go",
    ],
    importpath = "github.com/latticebuild/rules_supply_chain/supply_chain/private/tools/internal/purl",
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "@platforms//os:macos": [],
        "@platforms//os:windows": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    visibility = ["//supply_chain/private/tools:__subpackages__"],
)

go_test(
    name = "unit_test",
    srcs = [
        "purl_test.go",
    ],
    embed = [":lib"],
    pure = "on",
    race = "off",
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "@platforms//os:macos": [],
        "@platforms//os:windows": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)

go_test(
    name = "unit_race_test",
    srcs = [
        "purl_test.go",
    ],
    embed = [":lib"],
    pure = "off",
    race = "on",
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "@platforms//os:macos": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)

test_suite(
    name = "runtime_test",
    tests = [
        ":unit_race_test",
        ":unit_test",
    ],
    visibility = ["//supply_chain/private/tools:__pkg__"],
)
